### ISSUE TITLE
Q/A

### ISSUE THREAD

**Issue by haileydhanens** [haileydhanens/CWU_AriGato#19]
ask NAO more questions

part of working on this module set will be brain storming a larger question set
think of how you can integrate the use of existing external API's

**Comment by derek-vaughan** [comment]
I'd like to take this on as a side project to the emotional responses. I'm thinking of having somewhere between 10-20 "simple" questions similar to "How old are you" or "How are you", that don't require http requests or anything complex to implement. I think this will make interacting with NAO a bit more fun, and should be really easy to do.

 I'll start brainstorming questions and we can discuss at a meeting soon.

**Comment by htmlcc92** [comment]
OMDb works more or less now, need to see if we can upload the movie list to the robot. Works with switch and speech recognition, can't get parameters to work.

**Comment by derek-vaughan** [comment]
One thing that was suggested to me was having the NAO robot give out information about the CS department, or individual CS classes. I really liked this idea. For example, a question could be "What sort of CS electives are available?" or "Hey NAO, what did you think about CS 301?" (he could reply and say he learned about binary search trees for example). Thought this was a pretty cool idea!

**Comment by derek-vaughan** [comment]
I've started on the module where NAO gives information about CS classes. NAO kept overheating, and I was having issues with getting the switch statement to work with speech recognition, so i'll try again tomorrow or next week when NAO's cooled off.

You can find the preliminary work under the "InProgress" folder under "ClassKnowledge"

**Comment by haileydhanens** [comment]
Sufficient modules have been made
