### ISSUE TITLE
voice command as parameters

### ISSUE THREAD

**Issue by haileydhanens** [haileydhanens/CWU_AriGato#21]
figure out how nao can take voice commands as parameters and implement it in existing modules (change take step forward to take 'x' steps forward"

**Comment by MattSHarker** [comment]
I have completed a very basic version of this program, and have gotten it to work on the robot. It starts by asking which direction to move in (forwards, backward, left, or right), then which unit of measurement is being used (feet or inches) then asks how many units it's going to move (1-12). After it  gets proper responses for all of these questions, it will move in the correct direction the requested distance.
