### ISSUE TITLE
walk in directions

### ISSUE THREAD

**Issue by haileydhanens** [haileydhanens/CWU_AriGato#22]
-take step backwards
-take step to left
-take step to right
-turn 'x' degrees

-Hey matt, i just assigned this to you without asking because you did the take step forward module. if this is a problem just unassign yourself from the module or say something to me

**Comment by MattSHarker** [comment]
This is now Completed. It can be found under the name VariableWalk in the completed folder

**Comment by haileydhanens** [comment]
variable walk is done, but move directions still needs to be implemented

**Comment by haileydhanens** [comment]
modules have been uploaded onto the robot
