### ISSUE TITLE
Basic facial recognition

### ISSUE THREAD

**Issue by haileydhanens** [haileydhanens/CWU_AriGato#23]
Angie figured out how to get this to work. follow the online instructions she sent a link to, or just ask her for help if you see her in the lab

**Comment by angelanquach** [comment]
Updated the default case: "I don't think we've met yet."

**Comment by haileydhanens** [comment]
changed module to temperature. another module will have to be made to get the full weather, but I will count this module as a success. this module can be reopened later to finish the weather module
