### ISSUE TITLE
Pick up a ball

### ISSUE THREAD

**Issue by haileydhanens** [haileydhanens/CWU_AriGato#25]
NAO has a red ball API, so interacting with a red ball is something NAO should be able to do

**Comment by derek-vaughan** [comment]
On hold for now. The red ball tracker does not seem to be super reliable so far, though it's very likely that's just because of the red ball i've been using to test. We need to get a bigger ball that does not have any other colors on it and then continue with this module.

**Comment by haileydhanens** [comment]
are we just giving up on this one?

**Comment by derek-vaughan** [comment]
We can discuss more at our meeting later today, but unless someone would like to pick up on this module where I left off, I think it would be best to stop working on it. I've spent a decent amount of hours trying to get it to work (following the exact RedBallTracker code provided by NAO's documentation, as well as trying my own things), but I cant get it to work even semi-reliably. I think it'd be best to focus on refining what we have completed already, as well as the documentation.
