### ISSUE TITLE
movement with repetative motion

### ISSUE THREAD

**Issue by haileydhanens** [haileydhanens/CWU_AriGato#28]
ie dancing, tapping his foot.

**Comment by haileydhanens** [comment]
Angie is currently working on making NAO dance

**Comment by angelanquach** [comment]
Modeled on the timeline. Need to match it up to the beats of the song/routine.

**Comment by haileydhanens** [comment]
Dance routine completed by angie

**Comment by derek-vaughan** [comment]
Dancing/Pushups have been successfully tested and integrated.
