### ISSUE TITLE
Balance on one foot

### ISSUE THREAD

**Issue by haileydhanens** [haileydhanens/CWU_AriGato#32]
robot squats after he finishes. when squat is removes he moves to quickly to a standing position, which is dangerous. the stopping module is difficult to integrate with it. try to figure out a way to get him to gently go back to a standing position without squatting

**Comment by derek-vaughan** [comment]
Working on this. I've got the motion of him going back to the standard standing position to be a bit more fluid, but he still sort of wobbles back and forth. We'll have to check it out as a team and see if it's acceptable. Otherwise, more research will have to be done.

**Comment by derek-vaughan** [comment]
Motion has been smoothed out. Both raise foot modules are ready for re-integration.
