### ISSUE TITLE
Finish documentation/user manual

### ISSUE THREAD

**Issue by derek-vaughan** [haileydhanens/CWU_AriGato#35]
We're going to have to create a pretty in-depth user manual for NAO. It would be wise to get started on this early. I figured we can use a similar format/styling to our SRS and midterm progress report.

**Comment by derek-vaughan** [comment]
I've started on the documentation/user manual document. Mainly just created the layout and section headers, as well as migrating some of Hailey's written up documentation into this new document. Will continue to work on this in the next few days.

**Comment by derek-vaughan** [comment]
Documentation is nearing completion for at least the modules we currently have completed. Still need to add some descriptons/verbal queues for some modules, finish the "make your own module" section, and finish the "troubleshooting/faq" section.

**Comment by haileydhanens** [comment]
everything is looking good, we just need Angie to take a look at the problems section, and when everyone says they are done I can finalize the table of contents.

**Comment by derek-vaughan** [comment]
If everyone could read through the documentation one last time and make any final changes that'd be great! Afterwords, Hailey has volunteered to make the final updates to all of the tables of contents. So close to being done!
