### ISSUE TITLE
Lift L. Foot

### ISSUE THREAD

**Issue by haileydhanens** [haileydhanens/CWU_AriGato#5]
Make NAO Lift his left foot when asked

**Comment by derek-vaughan** [comment]
Command is integrated onto the robot, however it seems to put NAO into an infinite loop for some reason. Will attempt to fix this weekend.

**Comment by derek-vaughan** [comment]
Infinite loop big fixed. Completed module and integrated onto NAO as of 9:40am, 1/22/2019.
